root: /

Home: /
Archives: /archives
About: /about

language: en

author: iGuan7u
bio: Be yourself
description: A beautiful & simple theme.

disqus:
  enable: false
  shortname: iguan7u

google_site_verification:
google_analytics:

ICPLicense:
  enable: true
  content: 粤ICP备16128736号-2

mta_analytics:
  enable: enable
  name: MTAH5
  sid: 500681628

node_sass:
  # outputStyle: nested
  outputStyle: compressed
  precision: 5
  sourceComments: false