root: /

Home: /
Archives: /archives
About: /about

language: en

author: iGuan7u
description: A beautiful & simple theme.

gitalk:
  enable: true
  clientID: 065e38d669f0fa5bff9b
  clientSecret: 2440e8baec3aec1410a09c994bfb9d53891e04b4
  repo: iguan7u.github.io
  owner: iGuan7u
  admin: iGuan7u

disqus:
  enable: false
  shortname: iguan7u

ICPLicense:
  enable: true
  content: 粤ICP备16128736号-2

mta_analytics:
  enable: true
  name: MTAH5
  sid: 500681628

baidu_analytics:
  enable: false
  id: baidu_analytice_id

google_analytice:
  enable: false
  tracking_id: google_tracking_id

extra_plugin:
  enable: false
  url: extra_plugin_js_url

node_sass:
  # outputStyle: nested
  outputStyle: compressed
  precision: 5
  sourceComments: false