root: /

Home: /
Archives: /archives
About: /about

language: en

author: iGuan7u
description: A beautiful & simple theme.

gitalk:
  enable: false
  clientID: github_clientID
  clientSecret: github_clientSecret
  repo: you site homepage
  owner: your username
  admin: same as [owner]

disqus:
  enable: true
  shortname: iguan7u

ICPLicense:
  enable: true
  content: 粤ICP备16128736号-2

mta_analytics:
  enable: true
  name: MTAH5
  sid: 500681628

baidu_analytics:
  enable: false
  id: baidu_analytice_id

google_analytice:
  enable: false
  tracking_id: google_tracking_id

extra_plugin:
  enable: false
  url: extra_plugin_js_url

node_sass:
  # outputStyle: nested
  outputStyle: compressed
  precision: 5
  sourceComments: false